[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  # Supabase Configuration
  # You need to set these in your Netlify dashboard under Site Settings > Environment Variables
  # NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
  # NEXT_PUBLIC_BASE_URL = "https://your-netlify-site.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

